import * as React from "react";
import Dialog from "@mui/material/Dialog";
import DialogContent from "@mui/material/DialogContent";
import DialogContentText from "@mui/material/DialogContentText";
import DialogTitle from "@mui/material/DialogTitle";

export default function LoginDialog({ open }) {
  return (
    <div>
      <Dialog open={open} onClose={() => {}}>
        <DialogTitle>Missing API Key</DialogTitle>
        <DialogContent>
          <DialogContentText>
            No API key was found. Use a special link generated by an admin to
            login.
          </DialogContentText>
        </DialogContent>
      </Dialog>
    </div>
  );
}
